services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: westudy-app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: westudy-mariadb
      DB_PORT: 3306
      DB_USER: westudy
      DB_NAME: westudy
      DB_PASS: study1234
      REDIS_HOST: westudy-redis
      REDIS_PORT: 6379

  mariadb:
    image: mariadb:11
    container_name: westudy-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: westudy
      MARIADB_USER: westudy
      MARIADB_PASSWORD: study1234

  redis:
    image: redis
    container_name: westudy-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
